seed: 42

wandb:
  project: embedding-level-guardrails
  entity: null # Uses default W&B account/team.
  mode: online

models:
  backbone: jhu-clsp/ettin-encoder-68m
  classifier:
    head_hidden_dim: 1024

supcon_loss:
  temperature: 0.1

optimizer:
  lr: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1.0e-8

scheduler:
  enabled: false
  start_factor: 0.01
  end_factor: 1.0
  total_iters: 9

data:
  hf_dataset_path: hf://datasets/allenai/wildguardmix/train/wildguard_train.parquet

tokenizer:
  max_length: 2048

training:
  models: all
  sampler:
    number_of_samples_per_category: 8
    batch_size: 32
    number_of_samples_per_epoch: 70_000
  loader:
    num_workers: 0
    pin_memory: true
    persistent_workers: true
  validation:
    fraction: 0.1
  epochs: 10
  device: auto
  precision: auto # auto, fp32, fp16, or bf16
  max_grad_norm: 1.0
  gradient_checkpointing: true
  output_dir: ${hydra:runtime.output_dir}

hydra:
  job:
    chdir: false
  run:
    dir: outputs/
